### ISSUE TITLE
Pagination Not Properly Adding Balloons

### ISSUE THREAD

**Issue by jeqostudios** [Jeqo-Studios/Bloons#36]
**Describe the bug**
If there's several balloons that fill multiple rows, balloons that end up in the first and last slots of each row don't properly register or get added into the next available slots.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a minimum of 11 balloons
2. Load plugin
3. Open the balloon menu
4. Balloons will appear normal, but 2 balloons will be missing for each row of added balloons.

**Expected behavior**
<br>
Balloons are supposed to be placed from slots 2-8 and skip slots 1 and 9 in each row.

**Comment by IanTapply22** [comment]
Fixed by [`2a8f91a` (#35)](https://github.com/Jeqo-Studios/Bloons/pull/35/commits/2a8f91a0461deedc9714b005b4818bd50d92a22e)
